// Generated by CoffeeScript 1.3.3
var siteDescription, siteKeywords, siteTitle;

siteTitle = this.getPreparedTitle();

siteKeywords = this.getPreparedKeywords();

siteDescription = this.getPreparedKeywords();

doctype(5);

html({
  lang: 'en'
}, function() {
  head(function() {
    meta({
      charset: 'utf-16'
    });
    meta({
      'http-equiv': 'content-type',
      content: 'text/html; charset=utf-8'
    });
    meta({
      'http-equiv': 'X-UA-Compatible',
      content: 'IE=edge,chrome=1'
    });
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    });
    meta({
      name: 'title',
      content: h(siteTitle)
    });
    meta({
      name: 'description',
      content: h(siteDescription)
    });
    meta({
      name: 'keywords',
      content: h(siteKeywords)
    });
    text(this.getBlock('meta').toHTML());
    title(siteTitle);
    link({
      href: "http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic",
      rel: "stylesheet",
      type: "text/css"
    });
    link({
      rel: 'stylesheet',
      href: '/vendor/reveal/css/main.css',
      type: 'text/css'
    });
    link({
      rel: 'stylesheet',
      href: '/vendor/reveal/css/theme/sky.css',
      type: 'text/css'
    });
    link({
      rel: 'stylesheet',
      href: '/vendor/reveal/lib/css/docco.css',
      type: 'text/css'
    });
    link({
      rel: 'stylesheet',
      href: '/vendor/reveal/css/print/paper.css',
      type: 'text/css',
      media: 'print'
    });
    return ie('lte IE9', function() {
      return script({
        async: 'async',
        src: 'http://html5shim.googlecode.com/svn/trunk/html5.js'
      });
    });
  });
  return body(function() {
    text(this.content);
    script({
      src: '/vendor/reveal/lib/js/showdown.js'
    });
    script({
      src: '/vendor/reveal/lib/js/classList.js'
    });
    script({
      src: '/vendor/reveal/lib/js/head.min.js'
    });
    script({
      src: '/vendor/reveal/lib/js/highlight.js'
    });
    script({
      src: '/vendor/reveal/lib/js/html5shiv.js'
    });
    script({
      src: '/vendor/reveal/lib/js/showdown.js'
    });
    script({
      src: '/vendor/reveal/js/reveal.js'
    });
    script({
      type: 'text/javascript'
    }, function() {
      return "Reveal.initialize({\n	// Display controls in the bottom right corner\n	controls: true,\n\n	// Display a presentation progress bar\n	progress: true,\n\n	// Push each slide change to the browser history\n	history: true,\n\n	// Enable keyboard shortcuts for navigation\n	keyboard: true,\n\n	// Enable the slide overview mode\n	overview: true,\n\n	// Loop the presentation\n	loop: false,\n\n	// Number of milliseconds between automatically proceeding to the\n	// next slide, disabled when set to 0\n	autoSlide: 0,\n\n	// Enable slide navigation via mouse wheel\n	mouseWheel: true,\n\n	// Apply a 3D roll to links on hover\n	rollingLinks: true,\n\n	// Transition style\n	transition: 'default' // default/cube/page/concave/linear(2d)\n});";
    });
    return script("var _gaq = _gaq || [];\n_gaq.push(['_setAccount', 'UA-15502477-7']);\n_gaq.push(['_trackPageview']);\n(function() {\n	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n})();");
  });
});
